//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_ban_sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIETSACH
    {
        public string MaTG { get; set; }
        public string Masach { get; set; }
        public string vaitro { get; set; }
        public string vitri { get; set; }
    
        public virtual SACH_ SACH_ { get; set; }
        public virtual TACGIA TACGIA { get; set; }
    }
}
